### ISSUE TITLE
manifest.json has chunk id's instead of names, so processing fails

### ISSUE THREAD

**Issue by patroza** [AnujRNair/webpack-after-chunk-hash-plugin#1]
Using https://github.com/soundcloud/chunk-manifest-webpack-plugin
my manifest.json looks like:
```
 {
  "0": "app.35dfe07.chunk.js",
  "1": "aurelia.8c16c57.chunk.js",
  "2": "vendor.d34deea.chunk.js"
}
```

the code would suggest it should look like:
```
{
  "app": "app.35dfe07.chunk.js",
  "aurelia": "aurelia.8c16c57.chunk.js",
  "vendor": "vendor.d34deea.chunk.js"
}
```

I adjusted the plugin by searching manifest.json for `chunk.id`, instead of `chunk.name`

**Comment by AnujRNair** [comment]
Hi @patroza - thanks for reporting!

I opened a PR with a potential fix for this issue - can you let me know if you think it fixes this issue? If so, I will merge into master

https://github.com/AnujRNair/webpack-after-chunk-hash-plugin/pull/3

Thanks!

**Comment by AnujRNair** [comment]
Merged https://github.com/AnujRNair/webpack-after-chunk-hash-plugin/pull/3
Please let me know if you still experience this issue
